baseurl: "/"
title: Ricardo Landolt
theme: hugo-coder-portfolio
DefaultContentLanguage: en
paginate: 20
pygmentsstyle: b2
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
pygmentsUseClasses: yes
disqusShortname: yourdiscussshortname
params:
  author: Ricardo Landolt
  avatarurl: img/ricardo.jpg
  custom_css: []
  description: Ricardo Landolt's personal website
  hideCopyright: no
  hideCredits: no
  info: PASSIONATE R PROGRAMMER
  itemscentered: yes
  keywords: blog,developer,personal
  langseparator: '|'
  rtl: no
  snsShare: yes
  social:
    - icon: fab fa-github
      name: Github
      url: https://github.com/ricilandolt
      weight: 1
    - icon: fa fa-envelope
      name: Mail
      url: mailto:ricardo.landot1@gmail.com
      weight: 2
    - icon: fab fa-linkedin
      name: LinkedIn
      url: https://ch.linkedin.com/in/ricardo-landolt/
      weight: 3

languages:
  en:
    languagecode: en
    languagename: English
    menu:
      main:
        - name: About
          url: about
          weight: 1
        - name: Blog
          url: posts
          weight: 2
        - name: Projects
          url: projects
          weight: 3
        - name: Contact me
          url: contact
          weight: 5
    params:
      author: Ricardo Landolt
      description: Ricardo Landolt's personal website
      info: PASSIONATE R PROGRAMMER
      keywords: blog,developer,personal
    title: Ricardo Landolt

